export const catageories = [
  { id: 1, name: "Paper and Cardboard" },
  ,
  { id: 2, name: "Plastic" },
  { id: 3, name: "Metal" },
  { id: 4, name: "e-Waste" },
  { id: 5, name: "Vehicle" },
  { id: 6, name: "Others" },
];

export const bidproductcategories = [
  { name: "Machinery", sub: [{ name: "Used Machines" }] },
  {
    name: "Fabric",
    sub: [
      { name: "Other Fabric" },
      { name: "PVC Coated" },
      { name: "Canvas Lot" },
      { name: "Lace Lot" },
      { name: "Chiffon Lot" },
      { name: "Satin Lot" },
      { name: "Velvet Lot" },
      { name: "Denim Lot" },
      { name: "Linen Lot" },
      { name: "Wool Lot" },
      { name: "Silk Lot" },
      { name: "Rayon Lot" },
      { name: "Nylon Lot" },
      { name: "Polyester Lot" },
      { name: "Cotton Lot" },
    ],
  },
  {
    name: "Paper",
    sub: [
      { name: "Other Paper" },
      { name: "Stocklot Paper" },
      { name: "Coated Paper" },
      { name: "Kraft Paper" },
      { name: "Sorted Office Paper" },
      { name: "Newsprint" },
      { name: "OCC" },
      { name: "Mixed Paper" },
    ],
  },
  { name: "Wood", sub: [{ name: "Other" }] },
  {
    name: "Metal",
    sub: [
      { name: "Other Metal" },
      { name: "Iron" },
      { name: "Tin" },
      { name: "Nickel" },
      { name: "Lead" },
      { name: "Zinc" },
      { name: "Copper" },
      { name: "Aluminium" },
      { name: "Steel" },
    ],
  },
  {
    name: "Plastic",
    sub: [
      { name: "Co-polyester" },
      { name: "CA(Cellulose Acetale)" },
      { name: "ASA" },
      { name: "TPU" },
      { name: "TPO" },
      { name: "TPE" },
      { name: "PVA" },
      { name: "PS" },
      { name: "Polyester" },
      { name: "Polycarbonate" },
      { name: "PLA" },
      { name: "PETG" },
      { name: "PBT" },
      { name: "Nylon (PA)" },
      { name: "Noryl" },
      { name: "Mixed Rigid Plastic (MRP)" },
      { name: "LLDPE" },
      { name: "HMW" },
      { name: "HIPS" },
      { name: "GPPS" },
      { name: "EVA" },
      { name: "EPS" },
      { name: "Bopp" },
      { name: "ABS" },
      { name: "Polycarbonate (PC)" },
      { name: "Other" },
      { name: "Mix" },
      { name: "Acrylic" },
      { name: "Polypropylene (PP)" },
      { name: "LDPE" },
      { name: "PET/PETE" },
      { name: "HDPE" },
      { name: "PVC" },
    ],
  },
];
