export const indianStatesData = [
    { id: 1, name: "Andhra Pradesh", label: "Andhra Pradesh" },
    { id: 2, name: "Arunachal Pradesh", label: "Arunachal Pradesh" },
    { id: 3, name: "Assam", label: "Assam" },
    { id: 4, name: "Bihar", label: "Bihar" },
    { id: 5, name: "Chhattisgarh", label: "Chhattisgarh" },
    { id: 6, name: "Goa", label: "Goa" },
    { id: 7, name: "Gujarat", label: "Gujarat" },
    { id: 8, name: "Haryana", label: "Haryana" },
    { id: 9, name: "Himachal Pradesh", label: "Himachal Pradesh" },
    { id: 10, name: "Jharkhand", label: "Jharkhand" },
    { id: 11, name: "Karnataka", label: "Karnataka" },
    { id: 12, name: "Kerala", label: "Kerala" },
    { id: 13, name: "Madhya Pradesh", label: "Madhya Pradesh" },
    { id: 14, name: "Maharashtra", label: "Maharashtra" },
    { id: 15, name: "Manipur", label: "Manipur" },
    { id: 16, name: "Meghalaya", label: "Meghalaya" },
    { id: 17, name: "Mizoram", label: "Mizoram" },
    { id: 18, name: "Nagaland", label: "Nagaland" },
    { id: 19, name: "Odisha", label: "Odisha" },
    { id: 20, name: "Punjab", label: "Punjab" },
    { id: 21, name: "Rajasthan", label: "Rajasthan" },
    { id: 22, name: "Sikkim", label: "Sikkim" },
    { id: 23, name: "Tamil Nadu", label: "Tamil Nadu" },
    { id: 24, name: "Telangana", label: "Telangana" },
    { id: 25, name: "Tripura", label: "Tripura" },
    { id: 26, name: "Uttar Pradesh", label: "Uttar Pradesh" },
    { id: 27, name: "Uttarakhand", label: "Uttarakhand" },
    { id: 28, name: "West Bengal", label: "West Bengal" }
  ];
  