const AdminWallet = [

    {
        id : 1,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Aditya",
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Received',
        mode : 'Bank',
        ecopoints : '2000',
        wallet : '2000',
        income : '0',
        status : 'In',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Added In Wallet',

    },


    {
        id : 2,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Aditya",
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Received',
        mode : 'Wallet',
        ecopoints : '10',
        wallet : '1990',
        income : '10',
        status : 'In',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Lead/Subs.Charges',

    },

    {
        id : 3,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Nawaz",
        userid : '65432',
        usertype : 'User',
        tnxtype : 'Received ',
        mode : 'bank',
        ecopoints : '3000',
        wallet : '3000',
        income : '0',
        status : 'In',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Added In Wallet',

    },

    {
        id : 4,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Nawaz",
        userid : '65432',
        usertype : 'User',
        tnxtype : 'Paid',
        mode : 'Bank',
        ecopoints : '2500',
        wallet : '500',
        income : '0',
        status : 'Out',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Withdraw From Wallet',

    },


    {
        id : 5,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Aditya",
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Received  ',
        mode : 'Wallet',
        ecopoints : '500',
        wallet : '1490',
        income : '0',
        status : 'In',
        walettnxId : '989898983',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Paid To User',

    },

    {
        id : 6,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Nawaz",
        userid : '65432',
        usertype : 'User',
        tnxtype : 'Paid',
        mode : 'Wallet',
        ecopoints : '500',
        wallet : '1000',
        income : '0',
        status : 'Out',
        walettnxId : '989898983',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Received From KabadiWala',

    },
    
    {
        id : 7,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Aditya",
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Received   ',
        mode : 'Wallet',
        ecopoints : '10',
        wallet : '1480',
        income : '10',
        status : 'In',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Lead/Subs. Charges',

    },
    
    {
        id : 8,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Aditya",
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Cash   ',
        mode : 'Cash',
        ecopoints : '500',
        wallet : '1480',
        income : '10',
        status : 'Done',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Cash Purchase',

    },


    {
        id : 9,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Faiz",
        userid : '987843',
        usertype : 'Kabadiwala',
        tnxtype : 'Received    ',
        mode : 'Wallet',
        ecopoints : '10',
        wallet : '10',
        income : '10',
        status : 'Due',
        walettnxId : '124463',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Lead/Subs. Charges',

    },


    {
        id : 10,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Faiz",
        userid : '987843',
        usertype : 'Kabadiwala',
        tnxtype : 'Received',
        mode : 'Wallet',
        ecopoints : '800',
        wallet : '810',
        income : '0',
        status : 'Due',
        walettnxId : '86970079',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Paid to User',

    },


    {
        id : 11,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Nawaz",
        userid : '65432',
        usertype : 'User    ',
        tnxtype : 'Paid',
        mode : 'Wallet',
        ecopoints : '800',
        wallet : '810',
        income : '0',
        status : 'In',
        walettnxId : '86970079',
        invoice : 'OPO2134587',
        banktnxId : '857428',
        details : 'Received From KabadiWala',

    },
    
    

    {
        id : 12,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Faiz",
        userid : '987843',
        usertype : 'Kabadiwala    ',
        tnxtype : 'Received     ',
        mode : 'Bank',
        ecopoints : '1500',
        wallet : '690',
        income : '0',
        status : 'In',
        walettnxId : '86970079',
        invoice : 'OPO2134587',
        banktnxId : '3557887',
        details : 'Added In Wallet',

    },
    
    {
        id : 13,
        img : '/images/customImg/team-3.jpg',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        username : "Gayatri",
        userid : '18769',
        usertype : 'User    ',
        tnxtype : 'Paid',
        mode : 'Wallet',
        ecopoints : '200',
        wallet : '200',
        income : '200',
        status : 'Out',
        walettnxId : '9668',
        invoice : 'OPO2134587',
        banktnxId : '3557887',
        details : 'Promotional',

    },

]

export default AdminWallet ;