const UserWalletData = [
    {
        id : 1,
        date : '21 March 2023',
        time : 'At 8:45 PM',
        img2 : '/images/customImg/team-3.jpg',
        from : 'Aditya',
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Received',
        mode : "Wallet",
        ecopoints : '500',
        wallet : '500',
        income : '0',
        status : 'In',
        tnxid : '99858478',
        banktnxid : '857428',
        invoice : 'OPO2134587', 
        details : 'Waste Sold',
    },

    {
        id : 2,
        date : '21 March 2023',
        time : 'At 8:45 PM',
        img2 : '/images/customImg/wallet-2.png',
        from : 'Wallet',
        userid : '_',
        usertype : '_',
        tnxtype : 'Received',
        mode : "Bank",
        ecopoints : '1000',
        wallet : '1500',
        income : '0',
        status : 'In',
        tnxid : '124464',
        banktnxid : '3557887',
        invoice : 'OPO2134587', 
        details : 'Added In Wallete',
    },


    {
        id : 3,
        date : '21 March 2023',
        time : 'At 8:45 PM',
        img2 : '/images/customImg/team-3.jpg',
        from : 'Neha',
        userid : '78596',
        usertype : 'User',
        tnxtype : 'Paid',
        mode : "Wallet",
        ecopoints : '800',
        wallet : '700',
        income : '0',
        status : 'Out',
        tnxid : '124468',
        banktnxid : '_',
        invoice : 'OPO2134587', 
        details : 'Transfer to another User',
    },


    {
        id : 4,
        date : '21 March 2023',
        time : 'At 8:45 PM',
        img2 : '/images/customImg/wallet-2.png',
        from : 'Wallet',
        userid : '_',
        usertype : '_',
        tnxtype : 'Paid',
        mode : "Wallet",
        ecopoints : '500',
        wallet : '200',
        income : '0',
        status : 'Out',
        tnxid : '124470',
        banktnxid : '3557890',
        invoice : 'OPO2134587', 
        details : 'Widthdraw From Wallet',
    },


    {
        id : 5,
        date : '21 March 2023',
        time : 'At 8:45 PM',
        img2 : '/images/customImg/team-3.jpg',
        from : 'Aditya',
        userid : '12345',
        usertype : 'Kabadiwala',
        tnxtype : 'Received',
        mode : "Cash",
        ecopoints : '1000',
        wallet : '200',
        income : '0',
        status : 'Done',
        tnxid : '124473',
        banktnxid : '3557890',
        invoice : 'OPO2134587', 
        details : 'Waste Sold in Cash',
    },

]

export default UserWalletData ;