const UserWalletData = [

    {
         id : 1,
         img : '/images/customImg/team-3.jpg',
        img2 : '/images/customImg/wallet-2.png',
         date : '21 March 2023',
        time : 'At 8:45 PM',
        from : 'Aditya',
        to : 'Your Wallet',
        uniqueID : '123445',
        uniqueID2 : '654321',
        usertype : 'Kabadiwala',
        usertype2 : 'User',
        tnxtype : 'Wallet',
        amount : '+500',
        balance : '500',
        status : 'Received',
        walettnxId : '124463',
        banktnxId : '857428',
        invoice : 'OPO2134587',

    },


    {
        id : 2,
        img : '/images/customImg/bank-img.png',
        img2 : '/images/customImg/wallet-2.png',
        date : '21 March 2023',
       time : 'At 8:45 PM',
       from : 'Bank',
       to : 'Your Wallet',
       uniqueID : '25087431',
       uniqueID2 : '25087435',
       usertype : '_',
       usertype2 : 'User',
       tnxtype : 'Wallet',
       amount : '+1000',
       balance : '1500',
       status : 'In',
       walettnxId : '124463',
       banktnxId : '857428',
        invoice : 'OPO2134587',

   },


   {
    id : 3,
    img : '/images/customImg/wallet-2.png',
    img2 : '/images/customImg/footer-bg-1.png',
    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Your Wallet',
   to : 'TGSS',
   uniqueID : '25087431',
   uniqueID2 : '_',
   usertype : 'User',
   usertype2 : 'Admin',
   tnxtype : 'Wallet',
   amount : '-500',
   balance : '1000',
   status : 'Paid',
   walettnxId : '124463',
   banktnxId : '857428',
   invoice : 'OPO2134587',

},


{
    id : 4,
    img : '/images/customImg/c-1.jpg',
    img2 : '/images/customImg/wallet-2.png',
    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Nawaz',
   to : 'Your Wallet',
   uniqueID : '25087431',
   uniqueID2 : '25087435',
   usertype : 'User',
   usertype2 : 'User',
   tnxtype : 'Cash',
   amount : '+500',
   balance : '1500',
   status : 'In',
   walettnxId : '124463',
   banktnxId : '857428',
   invoice : 'OPO2134587',

},

{
    id : 5,
    img : '/images/customImg/wallet-2.png',
    img2 : '/images/customImg/footer-bg-1.png',
    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Your Wallet',
   to : 'TGSS',
   uniqueID : '25087431',
   uniqueID2 : '25087435',
   usertype : 'User',
   usertype2 : 'Admin',
   tnxtype : 'Cash',
   amount : '-500',
   balance : '1000',
   status : 'Out',
   walettnxId : '124463',
   banktnxId : '857428',
   invoice : 'OPO2134587',

},


{
    id : 6,
    img : '/images/customImg/wallet-2.png',
    img2 : '/images/customImg/bank-img.png',
    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Your Wallet',
   to : 'Bank',
   uniqueID : '25087431',
   uniqueID2 : '_',
   usertype : 'User',
   usertype2 : '_',
   tnxtype : 'Wallet',
   amount : '-1000',
   balance : '0',
   status : 'Out',
   walettnxId : '124463',
   banktnxId : '857428',
   invoice : 'OPO2134587',

},



{
    id : 7,
    img : '/images/customImg/footer-bg-1.png',
    img2 : '/images/customImg/wallet-2.png',
    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'TGSS',
   to : 'Your Wallet',
   uniqueID : '_',
   uniqueID2 : '25087435',
   usertype : 'Admin',
   usertype2 : 'User',
   tnxtype : 'Return',
   amount : '+500',
   balance : '500',
   status : 'Received',
   walettnxId : '124463',
   banktnxId : '857428',
   invoice : 'OPO2134587',


},

    // {
    //     id : 1,
    //     img : '/images/customImg/bank-img.jpg',
    //     name : 'Your Bank',
    //     uniqueID : '25087431',
    //     uniqueID2 : '25087435',
    //     company : 'Brand Orbiter',
    //     bankname : ' Kotak Bank',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',
    //     usertype : "Bank",
    //     transactiontype  : "Wallet",
    //     amountdebit : "500",
    //     amountcredit : "_",
    //     balance : "500",
    //     cmision : "₹20",
    //     wallet : 'Your Wallet',

    // },


    // {
    //     id : 2,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : " 400",
    //     amountcredit : "_",
    //     balance : "900",
    //     cmision : "₹10",

    // },


    // {
    //     id : 3,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "600",
    //     amountcredit : "_",
    //     balance : "1500",
    //     cmision : "₹15",

    // },

    // {
    //     id : 4,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'payment',
    //     status : 'payment',
    //     color_Status : 'orange',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "_",
    //     amountcredit : "200",
    //     balance : "1300",
    //     cmision : "₹5",

    // },

    // {
    //     id : 5,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'failed',
    //     status : 'Failed',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "_",
    //     amountcredit : "300",
    //     balance : "1000",
    //     cmision : "₹10",

    // },

    // {
    //     id : 6,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'failed',
    //     status : 'Failed',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "200",
    //     amountcredit : "_",
    //     balance : "1200",
    //     cmision : "₹10",
    // },


   


    
]

export default UserWalletData ;