const WalletData = [

    {
         id : 1,
         img : '/images/customImg/wallet-2.png',

         date : '21 March 2023',
        time : 'At 8:45 PM',
        from : 'Wallet',
        uniqueID : '_',
        usertype : '_',
        tnxtype : 'Received',
        mode : 'Bank',
        ecopoints : '2000',
        wallet : '2000',
        income : '0',
        status : 'In',
        walettnxId : '124462',
        banktnxId : '124462',
        invoice : '_',
        details : 'Added In Wallet',
        bolean : false,

    },


    {
        id : 2,
        img : '/images/customImg/cmp-1.jpg',

        date : '21 March 2023',
       time : 'At 8:45 PM',
       from : 'Kabadpe',
       uniqueID : '_',
       usertype : 'Admin',
       tnxtype : 'Paid',
       mode : 'Wallet',
       ecopoints : '10',
       wallet : '1990',
       income : '0',
       status : 'Out',
       walettnxId : '124463',
       banktnxId : '_',
       invoice : '959595',
       details : 'Lead/Subs. Charges',
       bolean : true,

   },


   {
    id : 3,
    img : '/images/customImg/team-3.jpg',

    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Nawaz',
   uniqueID : '65432',
   usertype : 'User',
   tnxtype : 'Paid',
   mode : 'Wallet',
   ecopoints : '500',
   wallet : '1490',
   income : '0',
   status : 'Out',
   walettnxId : '124466',
   banktnxId : '_',
   invoice : '959598',
   details : 'Waste Purchase',
   bolean : true,

},

{
    id : 6,
    img : '/images/customImg/footer-bg-1.png',

    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Kabadpe',
   uniqueID : '_',
   usertype : 'Admin',
   tnxtype : 'Paid',
   mode : 'Wallet',
   ecopoints : '10',
   wallet : '5480',
   income : '0',
   status : 'Out',
   walettnxId : '124483',
   banktnxId : '_',
   invoice : '959627',
   details : 'Lead/Subs. Charges',
   bolean : true,

},

{
    id : 7,
    img : '/images/customImg/bank-img.jpg',

    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Bank',
   uniqueID : '_',
   usertype : '_',
   tnxtype : 'Paid',
   mode : 'Bank',
   ecopoints : '3400',
   wallet : '2080',
   income : '0',
   status : 'Out',
   walettnxId : '124487',
   banktnxId : '124987',
   invoice : '_',
   details : 'Withdraw From Wallet',
   bolean : false,

},


{
    id : 4,
    img : '/images/customImg/cmp-3.jpg',

    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Brand Orbiter',
   uniqueID : '987843',
   usertype : 'Frenchies',
   tnxtype : 'Received',
   mode : 'Wallet',
   ecopoints : '4000',
   wallet : '5490',
   income : '0',
   status : 'In',
   walettnxId : '124466',
   banktnxId : '_',
   invoice : '959612',
   details : 'Waste Sale',
   bolean : true,


},

{
    id : 5,
    img : '/images/customImg/client-01.jpg',

    date : '21 March 2023',
   time : 'At 8:45 PM',
   from : 'Neha',
   uniqueID : '78596',
   usertype : 'User',
   tnxtype : 'Paid',
   mode : 'Cash',
   ecopoints : '2000',
   wallet : '5490',
   income : '0',
   status : 'In',
   walettnxId : '_',
   banktnxId : '_',
   invoice : '959623',
   details : 'Waste Purchase in Cash',
   bolean : true,

},


//     {
//         id : 2,
//         img : '/images/customImg/wallet-2.png',
//         img2 : '/images/customImg/team-3.jpg',
//         date : '21 March 2023',
//        time : 'At 8:45 PM',
//        from : 'Your Wallet',
//        to : 'Nawaz',
//        uniqueID : '25087431',
//        uniqueID2 : '25087435',
//        usertype : 'Kabadiwala',
//        usertype2 : 'User',
//        tnxtype : 'Wallet',
//        amount : '-100',
//        balance : '1900',
//        status : 'Paid',
//        walettnxId : '124463',
//        banktnxId : '857428',
//         charge : '-10',
//         invoice : 'OPO2134587',

//    },


//    {
//     id : 3,
//     img : '/images/customImg/c-1.jpg',
//     img2 : '/images/customImg/wallet-2.png',
//     date : '21 March 2023',
//    time : 'At 8:45 PM',
//    from : 'Aditya',
//    to : 'Your Wallet',
//    uniqueID : '25087431',
//    uniqueID2 : '25087435',
//    usertype : 'Kabadiwala',
//    usertype2 : 'Kabadiwala',
//    tnxtype : 'Cash',
//    amount : '+500',
//    balance : '2400',
//    status : 'In',
//    walettnxId : '124463',
//    banktnxId : '857428',
//    invoice : 'OPO2134587',
//    charge : '0',

// },


// {
//     id : 4,
//     img : '/images/customImg/wallet-2.png',
//     img2 : '/images/customImg/client-01.png',
//     date : '21 March 2023',
//    time : 'At 8:45 PM',
//    from : 'Your Wallet',
//    to : 'Neha',
//    uniqueID : '25087431',
//    uniqueID2 : '25087435',
//    usertype : 'Kabadiwala',
//    usertype2 : 'User',
//    tnxtype : 'Cash',
//    amount : '-500',
//    balance : '1900',
//    status : 'Out',
//    walettnxId : '124463',
//    banktnxId : '857428',
//    invoice : 'OPO2134587',
//    charge : '-10',

// },

// {
//     id : 5,
//     img : '/images/customImg/cmp-3.jpg',
//     img2 : '/images/customImg/wallet-2.png',
//     date : '21 March 2023',
//    time : 'At 8:45 PM',
//    from : 'Brand Orbiter',
//    to : 'Your Wallet',
//    uniqueID : '25087431',
//    uniqueID2 : '25087435',
//    usertype : 'Frenchies',
//    usertype2 : 'Kabadiwala',
//    tnxtype : 'Wallet',
//    amount : '5000',
//    balance : '-2880',
//    status : 'Received',
//    walettnxId : '124463',
//    banktnxId : '857428',
//    invoice : 'OPO2134587',
//    charge : '0',

// },


// {
//     id : 6,
//     img : '/images/customImg/wallet-2.png',
//     img2 : '/images/customImg/team-3.jpg',
//     date : '21 March 2023',
//    time : 'At 8:45 PM',
//    from : 'Your Wallet',
//    to : 'Nawaz',
//    uniqueID : '25087431',
//    uniqueID2 : '25087435',
//    usertype : 'Kabadiwala',
//    usertype2 : 'User',
//    tnxtype : 'Wallet',
//    amount : '-3200',
//    balance : '300',
//    status : 'Paid',
//    walettnxId : '124463',
//    banktnxId : '857428',
//    invoice : 'OPO2134587',
//    charge : '-10',

// },



// {
//     id : 7,
//     img : '/images/customImg/wallet-2.png',
//     img2 : '/images/customImg/c-1.jpg',
//     date : '21 March 2023',
//    time : 'At 8:45 PM',
//    from : 'Your Wallet',
//    to : 'Aditya',
//    uniqueID : '25087431',
//    uniqueID2 : '25087435',
//    usertype : 'Kabadiwala',
//    usertype2 : 'bank',
//    tnxtype : 'Bank',
//    amount : '-2000',
//    balance : '1690',
//    status : 'Out',
//    walettnxId : '124463',
//    banktnxId : '857428',
//    invoice : 'OPO2134587',
//    charge : '0',


// },

    // {
    //     id : 1,
    //     img : '/images/customImg/bank-img.jpg',
    //     name : 'Your Bank',
    //     uniqueID : '25087431',
    //     uniqueID2 : '25087435',
    //     company : 'Brand Orbiter',
    //     bankname : ' Kotak Bank',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',
    //     usertype : "Bank",
    //     transactiontype  : "Wallet",
    //     amountdebit : "500",
    //     amountcredit : "_",
    //     balance : "500",
    //     cmision : "₹20",
    //     wallet : 'Your Wallet',

    // },


    // {
    //     id : 2,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : " 400",
    //     amountcredit : "_",
    //     balance : "900",
    //     cmision : "₹10",

    // },


    // {
    //     id : 3,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "600",
    //     amountcredit : "_",
    //     balance : "1500",
    //     cmision : "₹15",

    // },

    // {
    //     id : 4,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'payment',
    //     status : 'payment',
    //     color_Status : 'orange',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "_",
    //     amountcredit : "200",
    //     balance : "1300",
    //     cmision : "₹5",

    // },

    // {
    //     id : 5,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'failed',
    //     status : 'Failed',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "_",
    //     amountcredit : "300",
    //     balance : "1000",
    //     cmision : "₹10",

    // },

    // {
    //     id : 6,
    //     img : '/images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'failed',
    //     status : 'Failed',
    //     color_Status : 'green',
    //     usertype : "User",
    //     transactiontype  : "Wallet",
    //     amountdebit : "200",
    //     amountcredit : "_",
    //     balance : "1200",
    //     cmision : "₹10",
    // },


   


    
]

export default WalletData ;