const WalletData = [

    {
        id : 1,
        img : '/images/customImg/test-img-1.jpg',
        name : 'William Mardoch',
        company : 'Brand Orbiter',
        uniqueID : ' 25087431',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        uniqueID2 : 'OPO2134587',
        amount : '25650.00',
        category : 'receive',
        status : 'Receive',
        color_Status : 'green',
        usertype : "User",
        transactiontype  : "Wallet",
        amountdebit : "500",
        amountcredit : "_",
        balance : "500",
        cmision : "₹20",

    },


    {
        id : 2,
        img : '/images/customImg/client-01.png',
        name : 'William Mardoch',
        company : 'Brand Orbiter',
        uniqueID : ' 25087431',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        uniqueID2 : 'OPO2134587',
        amount : '25650.00',
        category : 'receive',
        status : 'Receive',
        color_Status : 'green',
        usertype : "User",
        transactiontype  : "Wallet",
        amountdebit : " 400",
        amountcredit : "_",
        balance : "900",
        cmision : "₹10",

    },


    {
        id : 3,
        img : '/images/customImg/client-01.png',
        name : 'William Mardoch',
        company : 'Brand Orbiter',
        uniqueID : ' 25087431',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        uniqueID2 : 'OPO2134587',
        amount : '25650.00',
        category : 'receive',
        status : 'Receive',
        color_Status : 'green',
        usertype : "User",
        transactiontype  : "Wallet",
        amountdebit : "600",
        amountcredit : "_",
        balance : "1500",
        cmision : "₹15",

    },

    {
        id : 4,
        img : '/images/customImg/client-01.png',
        name : 'William Mardoch',
        company : 'Brand Orbiter',
        uniqueID : ' 25087431',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        uniqueID2 : 'OPO2134587',
        amount : '25650.00',
        category : 'payment',
        status : 'payment',
        color_Status : 'orange',
        usertype : "User",
        transactiontype  : "Wallet",
        amountdebit : "_",
        amountcredit : "200",
        balance : "1300",
        cmision : "₹5",

    },

    {
        id : 5,
        img : '/images/customImg/client-01.png',
        name : 'William Mardoch',
        company : 'Brand Orbiter',
        uniqueID : ' 25087431',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        uniqueID2 : 'OPO2134587',
        amount : '25650.00',
        category : 'failed',
        status : 'Failed',
        color_Status : 'green',
        usertype : "User",
        transactiontype  : "Wallet",
        amountdebit : "_",
        amountcredit : "300",
        balance : "1000",
        cmision : "₹10",

    },

    {
        id : 6,
        img : '/images/customImg/client-01.png',
        name : 'William Mardoch',
        company : 'Brand Orbiter',
        uniqueID : ' 25087431',
        date : '21 March 2023',
        time : 'At 8:45 PM',
        uniqueID2 : 'OPO2134587',
        amount : '25650.00',
        category : 'failed',
        status : 'Failed',
        color_Status : 'green',
        usertype : "User",
        transactiontype  : "Wallet",
        amountdebit : "200",
        amountcredit : "_",
        balance : "1200",
        cmision : "₹10",
    },


    // {
    //     id : 6,
    //     img : './images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'withdraw',
    //     status : 'Withdraw',
    //     color_Status : 'orange',

    // },

    // {
    //     id : 7,
    //     img : './images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'withdraw',
    //     status : 'Withdraw',
    //     color_Status : 'orange',

    // },

    // {
    //     id : 8,
    //     img : './images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'receive',
    //     status : 'Receive',
    //     color_Status : 'green',

    // },

    // {
    //     id : 9,
    //     img : './images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'payment',
    //     status : 'Payment',
    //     color_Status : 'orange',

    // },

    // {
    //     id : 10,
    //     img : './images/customImg/client-01.png',
    //     name : 'William Mardoch',
    //     company : 'Brand Orbiter',
    //     uniqueID : ' 25087431',
    //     date : '21 March 2023',
    //     time : 'At 8:45 PM',
    //     uniqueID2 : 'OPO2134587',
    //     amount : '25650.00',
    //     category : 'withdraw',
    //     status : 'Withdraw',
    //     color_Status : 'orange',

    // },


    
]

export default WalletData ;